##05-RDataEngineer-03-Join    
library(dplyr)
vignette("two-table", package = "dplyr")
check_then_install("nycflights13", "0.1")
library(nycflights13)
View(airlines)
slice(flights, 1)
?left_join
View(weather)
answer02 <- left_join(answer01,weather)
View(answer02)
intersect(colnames(answer01),colnames(weather))
View(airports)
c("origin" = "faa")
answer03 <- left_join(answer02,airports, by = c("origin" = "faa"))
View(answer03)
answer04 <- left_join(answer03,airports, by = c("dest" = "faa"))
colnames(answer04)

View(answer02.3)
View(df1)
View(df2)
wiki_join()
left_join(df1, df2)
right_join(df2, df1)
inner_join(df1, df2)
full_join(df1, df2)
anti_join(df1, df2)
View(df3)
View(df4)
inner_join(df3, df4)
semi_join(df3, df4)

